/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_redis_sentinel_client_RedisClient */

#ifndef _Included_com_redis_sentinel_client_RedisClient
#define _Included_com_redis_sentinel_client_RedisClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    cinit
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_redis_sentinel_client_RedisClient_cinit
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    cget
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_redis_sentinel_client_RedisClient_cget
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    cmget
 * Signature: ([Ljava/lang/String;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_redis_sentinel_client_RedisClient_cmget
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    cmget2
 * Signature: ([Ljava/lang/String;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_redis_sentinel_client_RedisClient_cmget2
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    cset
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_redis_sentinel_client_RedisClient_cset__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    cmset
 * Signature: ([Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_redis_sentinel_client_RedisClient_cmset
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    cdel
 * Signature: ([Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_redis_sentinel_client_RedisClient_cdel___3Ljava_lang_String_2
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    cdel
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_redis_sentinel_client_RedisClient_cdel__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    clpush
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_redis_sentinel_client_RedisClient_clpush
  (JNIEnv *, jclass, jstring, jobjectArray);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    clrange
 * Signature: (Ljava/lang/String;II)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_redis_sentinel_client_RedisClient_clrange__Ljava_lang_String_2II
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    chget
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_redis_sentinel_client_RedisClient_chget
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    czadd
 * Signature: (Ljava/lang/String;ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_redis_sentinel_client_RedisClient_czadd
  (JNIEnv *, jclass, jstring, jint, jstring);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    czrange
 * Signature: (Ljava/lang/String;II)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_redis_sentinel_client_RedisClient_czrange
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    cRedisCommand
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_redis_sentinel_client_RedisClient_cRedisCommand__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    cRedisCommand
 * Signature: ([Ljava/lang/String;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_redis_sentinel_client_RedisClient_cRedisCommand___3Ljava_lang_String_2
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    cgetBytes
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_redis_sentinel_client_RedisClient_cgetBytes
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    csetBytes
 * Signature: ([B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_redis_sentinel_client_RedisClient_csetBytes
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    cset
 * Signature: (Ljava/lang/String;Ljava/lang/String;J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_redis_sentinel_client_RedisClient_cset__Ljava_lang_String_2Ljava_lang_String_2J
  (JNIEnv *, jclass, jstring, jstring, jlong);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    clrange
 * Signature: ([BII)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_redis_sentinel_client_RedisClient_clrange___3BII
  (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    cexists
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_redis_sentinel_client_RedisClient_cexists
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    ctype
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_redis_sentinel_client_RedisClient_ctype
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    csetnx
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_redis_sentinel_client_RedisClient_csetnx
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    cgetset
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_redis_sentinel_client_RedisClient_cgetset
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    cincr
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_redis_sentinel_client_RedisClient_cincr
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    cdecr
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_redis_sentinel_client_RedisClient_cdecr
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    cincrby
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_redis_sentinel_client_RedisClient_cincrby
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    cdecrby
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_redis_sentinel_client_RedisClient_cdecrby
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    cappend
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_redis_sentinel_client_RedisClient_cappend
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    crpush
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_redis_sentinel_client_RedisClient_crpush
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    cllen
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_redis_sentinel_client_RedisClient_cllen
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    cltrim
 * Signature: (Ljava/lang/String;II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_redis_sentinel_client_RedisClient_cltrim
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    clset
 * Signature: (Ljava/lang/String;ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_redis_sentinel_client_RedisClient_clset
  (JNIEnv *, jclass, jstring, jint, jstring);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    clrem
 * Signature: (Ljava/lang/String;ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_redis_sentinel_client_RedisClient_clrem
  (JNIEnv *, jclass, jstring, jint, jstring);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    clpop
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_redis_sentinel_client_RedisClient_clpop
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    crpop
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_redis_sentinel_client_RedisClient_crpop
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    csadd
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_redis_sentinel_client_RedisClient_csadd
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    csrem
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_redis_sentinel_client_RedisClient_csrem
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    cspop
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_redis_sentinel_client_RedisClient_cspop
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    csrandmember
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_redis_sentinel_client_RedisClient_csrandmember
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    cscard
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_redis_sentinel_client_RedisClient_cscard
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    csismember
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_redis_sentinel_client_RedisClient_csismember
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    csmembers
 * Signature: (Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_redis_sentinel_client_RedisClient_csmembers
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    czrem
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_redis_sentinel_client_RedisClient_czrem
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    czincrby
 * Signature: (Ljava/lang/String;ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_redis_sentinel_client_RedisClient_czincrby
  (JNIEnv *, jclass, jstring, jint, jstring);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    czrank
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_redis_sentinel_client_RedisClient_czrank
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    czrevrank
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_redis_sentinel_client_RedisClient_czrevrank
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    czrevrange
 * Signature: (Ljava/lang/String;II)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_redis_sentinel_client_RedisClient_czrevrange
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    czrangebyscore
 * Signature: (Ljava/lang/String;II)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_redis_sentinel_client_RedisClient_czrangebyscore
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    czcount
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_redis_sentinel_client_RedisClient_czcount__Ljava_lang_String_2II
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    czcard
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_redis_sentinel_client_RedisClient_czcard
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    czscore
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_redis_sentinel_client_RedisClient_czscore
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    czremrangebyrank
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_redis_sentinel_client_RedisClient_czremrangebyrank
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    czremrangebyscore
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_redis_sentinel_client_RedisClient_czremrangebyscore
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    chset
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_redis_sentinel_client_RedisClient_chset
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    chmget
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_redis_sentinel_client_RedisClient_chmget
  (JNIEnv *, jclass, jstring, jobjectArray);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    chincrby
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_redis_sentinel_client_RedisClient_chincrby
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    chexists
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_redis_sentinel_client_RedisClient_chexists
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    chdel
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_redis_sentinel_client_RedisClient_chdel
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    chlen
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_redis_sentinel_client_RedisClient_chlen
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    chkeys
 * Signature: (Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_redis_sentinel_client_RedisClient_chkeys
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    chvals
 * Signature: (Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_redis_sentinel_client_RedisClient_chvals
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_redis_sentinel_client_RedisClient
 * Method:    csetex
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_redis_sentinel_client_RedisClient_csetex
  (JNIEnv *, jclass, jstring, jstring, jint);


#ifdef __cplusplus
}
#endif
#endif
